name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx (to use advanced build features)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image to Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chimerichards/aws-demo:${{ github.sha }}

    # Deploy to Azure App Service
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myuniqueprefix-appservice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: 'chimerichards/aws-demo:${{ github.sha }}'
