name: Deploy to Azure App Service

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DEV # <-- Specify the environment here
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t chimerichards/aws-demo:latest .
          docker push chimerichards/aws-demo:latest

      # Deploy to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: myuniqueprefix-appservice
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} 
          images: 'chimerichards/aws-demo:latest'
