name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t chimerichards/aws-demo:latest .
          docker push chimerichards/aws-demo:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: DEV
    strategy:
      matrix:
        region: ["us-east-1", "eu-west-1"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Adjust .elasticbeanstalk configuration for region
        run: |
          sed -i "s/application_name: myapp/application_name: myapp-unique1234-${{ matrix.region }}/g" $GITHUB_WORKSPACE/.elasticbeanstalk/config.yml
          sed -i "s/default_region: us-east-1/default_region: ${{ matrix.region }}/g" $GITHUB_WORKSPACE/.elasticbeanstalk/config.yml

      - name: Deploy to Elastic Beanstalk in ${{ matrix.region }}
        run: |
          pip install awsebcli
          mkdir -p ~/.aws
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_KEY }}" >> ~/.aws/credentials
          echo "[default]" >> ~/.aws/config
          echo "region = ${{ matrix.region }}" >> ~/.aws/config
          eb deploy myenv-${{ matrix.region }}        
