name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t chimerichards/aws-demo:latest .
          docker push chimerichards/aws-demo:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: DEV
    strategy:
      matrix:
        region: ["us-east-1", "eu-west-1"]

    steps:
      - name: Generate .elasticbeanstalk configuration for region
        run: |
          mkdir -p .elasticbeanstalk
          echo "branch-defaults:" >> .elasticbeanstalk/config.yml
          echo "  main:" >> .elasticbeanstalk/config.yml
          echo "    environment: myenv-${{ matrix.region }}" >> .elasticbeanstalk/config.yml
          echo "environment-defaults:" >> .elasticbeanstalk/config.yml
          echo "  myenv:" >> .elasticbeanstalk/config.yml
          echo "    branch: null" >> .elasticbeanstalk/config.yml
          echo "    repository: null" >> .elasticbeanstalk/config.yml
          echo "global:" >> .elasticbeanstalk/config.yml
          echo "  application_name: myapp-unique1234-${{ matrix.region }}" >> .elasticbeanstalk/config.yml
          echo "  default_ec2_keyname: null" >> .elasticbeanstalk/config.yml
          echo "  default_platform: Docker running on 64bit Amazon Linux 2023" >> .elasticbeanstalk/config.yml
          echo "  default_region: ${{ matrix.region }}" >> .elasticbeanstalk/config.yml
          echo "  include_git_submodules: true" >> .elasticbeanstalk/config.yml
          echo "  instance_profile: null" >> .elasticbeanstalk/config.yml
          echo "  platform_name: null" >> .elasticbeanstalk/config.yml
          echo "  platform_version: null" >> .elasticbeanstalk/config.yml
          echo "  profile: null" >> .elasticbeanstalk/config.yml
          echo "  sc: git" >> .elasticbeanstalk/config.yml
          echo "  workspace_type: Application" >> .elasticbeanstalk/config.yml
      
      - name: Generate Dockerrun.aws.json
        run: |
          echo '{
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "chimerichards/aws-demo:latest",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": "80"
              }
            ]
          }' > Dockerrun.aws.json

      - name: Deploy to Elastic Beanstalk in ${{ matrix.region }}
        run: |
          pip install awsebcli
          mkdir -p ~/.aws
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_KEY }}" >> ~/.aws/credentials
          echo "[default]" >> ~/.aws/config
          echo "region = ${{ matrix.region }}" >> ~/.aws/config
          eb deploy myenv-${{ matrix.region }}

